/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:dd7d566f-fa8b-4b34-b6a6-dfeec925e9d4",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_pLh8bVffs",
    "aws_user_pools_web_client_id": "o0fdcgtbqju576jc2pqt963f5",
    "oauth": {}
};


export default awsmobile;
